export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"Home"},["/README.md"]],
  ["v-6c0089f0","/get-started.html",{"title":"Get Started"},[":md"]],
  ["v-6b6f3554","/backend-guide/get-started.html",{"title":"快速上手"},[":md"]],
  ["v-61ff12ca","/frontend-guide/installation.html",{"title":"安装"},[":md"]],
  ["v-2b4d762c","/frontend-guide/introduction.html",{"title":"概念"},[":md"]],
  ["v-5b95b768","/frontend-guide/quick-start.html",{"title":"快速上手"},[":md"]],
  ["v-68ae2b3c","/frontend-guide/action/serverAction.html",{"title":"服务器动作"},[":md"]],
  ["v-ea4734cc","/frontend-guide/action/viewAction.html",{"title":"视图动作"},[":md"]],
  ["v-3c258304","/frontend-guide/component/switch.html",{"title":"开关"},[":md"]],
  ["v-607c1484","/frontend-guide/field/string.html",{"title":"文本"},[":md"]],
  ["v-08477573","/frontend-guide/view/detail.html",{"title":"详情"},[":md"]],
  ["v-f8ad30c0","/frontend-guide/view/form.html",{"title":"表单"},[":md"]],
  ["v-6254e67c","/frontend-guide/view/search.html",{"title":"搜索"},[":md"]],
  ["v-4d1703c0","/frontend-guide/view/table.html",{"title":"表格"},[":md"]],
  ["v-0f3ddb46","/frontend-guide/mask/appFounder.html",{"title":"app Founder"},[":md"]],
  ["v-dc00b7da","/frontend-guide/mask/language.html",{"title":"多语言"},[":md"]],
  ["v-6e363128","/frontend-guide/mask/menu.html",{"title":"菜单"},[":md"]],
  ["v-429a5360","/frontend-guide/mask/message.html",{"title":"消息"},[":md"]],
  ["v-38223480","/frontend-guide/mask/user.html",{"title":"用户设置"},[":md"]],
  ["v-544ca0ec","/frontend-guide/layout/actionBar.html",{"title":"操作区"},[":md"]],
  ["v-9351a37e","/frontend-guide/layout/search.html",{"title":"搜索区"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
  ["v-12384e33","/category/history/",{"title":"category > History"},[]],
  ["v-3e5b7b84","/category/categorya/",{"title":"category > CategoryA"},[]],
  ["v-3e5b7ba3","/category/categoryb/",{"title":"category > CategoryB"},[]],
  ["v-3e5b7bc2","/category/categoryc/",{"title":"category > CategoryC"},[]],
  ["v-b301e1d8","/tag/wwi/",{"title":"tag > WWI"},[]],
  ["v-2962daa1","/tag/wwii/",{"title":"tag > WWII"},[]],
  ["v-06bbb262","/tag/tag-a/",{"title":"tag > tag A"},[]],
  ["v-06bbb224","/tag/tag-b/",{"title":"tag > tag B"},[]],
  ["v-06bbb1e6","/tag/tag-c/",{"title":"tag > tag C"},[]],
  ["v-06bbb1a8","/tag/tag-d/",{"title":"tag > tag D"},[]],
  ["v-06bbb16a","/tag/tag-e/",{"title":"tag > tag E"},[]],
  ["v-e52c881c","/article/",{"title":"article"},[]],
  ["v-01560935","/timeline/",{"title":"timeline"},[]],
  ["v-5bc93818","/category/",{"title":"category"},[]],
  ["v-744d024e","/tag/",{"title":"tag"},[]],
]
